#!/bin/bash -l
#SBATCH --partition regular
#SBATCH --constraint haswell
#SBATCH --nodes 20
#SBATCH --ntasks-per-node 1
#SBATCH --time 01:20:00
#SBATCH --license cscratch1
#SBATCH --mail-type ALL
#SBATCH --mail-user morelandjs@gmail.com
#SBATCH --output  /global/cscratch1/sd/jsm55/slurm/%x-%j
#SBATCH --error   /global/cscratch1/sd/jsm55/slurm/%x-%j

export CONDA_PREFIX=/global/common/software/m2730/qm18-partons
export PATH=$CONDA_PREFIX/bin:$PATH
export XDG_DATA_HOME=$CSCRATCH/share

workdir=$CSCRATCH/taskfarmer/$SLURM_JOB_NAME-$NERSC_HOST-$SLURM_JOB_ID
mkdir -p $workdir
cd $workdir

find $CSCRATCH/checkpoints/cori-8523207 -type f | sed 's/^/run-events checkpoint /' > tasks

module load taskfarmer
runcommands.sh tasks
