#!/bin/bash
#SBATCH --partition regular
#SBATCH --constraint haswell
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 1
#SBATCH --time 00:10:00
#SBATCH --license cscratch1
#SBATCH --mail-type ALL
#SBATCH --mail-user <user> 
#SBATCH --output  /global/cscratch1/sd/jsm55/slurm/%x-%j
#SBATCH --error   /global/cscratch1/sd/jsm55/slurm/%x-%j
#SBATCH --workdir /global/cscratch1/sd/jsm55/inputfiles

export CONDA_PREFIX=/global/common/software/m2730/qm18-partons
export PATH=$CONDA_PREFIX/bin:$PATH
export XDG_DATA_HOME=$CSCRATCH/share

module load parallel

TRENTO=~/hic-eventgen/nersc/qm18-partons/trento-wrapper
srun parallel --verbose $TRENTO  @{} ::: qm18-partons/main/pPb5020/*
