#!/bin/bash
#SBATCH --qos regular
#SBATCH --constraint haswell
#SBATCH --nodes 10
#SBATCH --cpus-per-task 64
#SBATCH --time 12:00:00
#SBATCH --license cscratch1
#SBATCH --mail-type ALL
#SBATCH --mail-user morelandjs@gmail.com
#SBATCH --output  /global/cscratch1/sd/jsm55/slurm/%x-%j
#SBATCH --error   /global/cscratch1/sd/jsm55/slurm/%x-%j

# export environment variables
export CONDA_PREFIX=/global/common/software/m2730/qm18-partons
export PATH=$CONDA_PREFIX/bin:$PATH
export XDG_DATA_HOME=$CSCRATCH/share
export THREADS=32

# run tasks
module load taskfarmer
runcommands.sh tasks
