#!/bin/bash
#SBATCH --partition regular
#SBATCH --constraint haswell
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 1
#SBATCH --time 05:00:00
#SBATCH --license cscratch1
#SBATCH --mail-type ALL
#SBATCH --mail-user morelandjs@gmail.com
#SBATCH --output /global/cscratch1/sd/jsm55/slurm/%x-%j
#SBATCH --error  /global/cscratch1/sd/jsm55/slurm/%x-%j

export CONDA_PREFIX=/global/common/software/m2730/qm18-partons
export PATH=$CONDA_PREFIX/bin:$PATH
export XDG_DATA_HOME=$CSCRATCH/share

module load parallel

find $CSCRATCH/checkpoints/cori-8523204 -type f | \
  srun parallel --verbose run-events checkpoint
