#!/bin/bash
#SBATCH --partition regular
#SBATCH --constraint haswell
#SBATCH --nodes 5
#SBATCH --cpus-per-task 1
#SBATCH --time 10:00:00
#SBATCH --license cscratch1
#SBATCH --mail-type ALL
#SBATCH --mail-user morelandjs@gmail.com
#SBATCH --output  /global/cscratch1/sd/jsm55/slurm/%x-%j
#SBATCH --error   /global/cscratch1/sd/jsm55/slurm/%x-%j
#SBATCH --workdir /global/cscratch1/sd/jsm55/inputfiles

export CONDA_PREFIX=/global/common/software/m2730/qm18-partons
export PATH=$CONDA_PREFIX/bin:$PATH
export XDG_DATA_HOME=$CSCRATCH/share

# broadcast executable to compute nodes (for large scale jobs)
exe=design-wrapper
sbcast ~/hic-eventgen/nersc/qm18-partons/$exe /tmp/$exe  # change source path to actual location

# change path to match all design input files
srun /tmp/$exe $(<reruns/parton_width_bug)
